name: Release

on:
  release:
    types: [published, created, edited]
  push:
    branches: [release-ci]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v2
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Setup sonatype credentials
        run: |
          echo "credentials += Credentials("Sonatype Nexus Repository Manager",
            "oss.sonatype.org",
            "${{ secrets.SONATYPE_USERNAME }}",
            "${{ secrets.SONATYPE_PASSWORD }}"
          )"
      - name: publishSigned
        run: sbt publishSigned
      - name: Push to sonatype
        run: sbt sonatypeBundleRelease
